insert into cozinha (id,nome) values (1,'Tailandesa')
insert into cozinha (id,nome) values (2,'Indiana')
insert into restaurante (nome,taxa_frete,cozinha_id) values ('Abc','5.10',1)
insert into restaurante (nome,taxa_frete,cozinha_id) values ('Def','7.50',1)
insert into restaurante (nome,taxa_frete,cozinha_id) values ('Ghi','7.50',2)